---
- name: Fail without 'version' attribute
  fail:
    msg: Failed installing python package {{ pkg }}. 'version' attribute required.
  when: not version
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=3600
- name: Install python venv for python {{ py_version }} to allow for software
        install inside virtual python environments
  apt:
    pkg: python{{ py_version }}-venv
- name: Prepare virtual env for {{ pkg }} python package version {{ version }}
  command: python{{ py_version }} -m venv {{ "--system-site-packages" if system_site_packages }} /opt/{{ dir }}-{{ version }}
  args:
    creates: /opt/{{ dir }}-{{ version }}
- name: Install {{ pkg }} python package version {{ version }}
  command: /opt/{{ dir }}-{{ version }}/bin/python -m pip install {{ pkg }}=={{ version }}
  args:
    creates: /opt/{{ dir }}-{{ version }}/bin/{{ bin if bin is string else bin[-1] }}
- name: Symlink default version {{ version }} for {{ pkg }} python package
  file:
    src: "{{ dir }}-{{ version }}"
    dest: "/opt/{{ dir }}"
    state: link
- name: Symlink binary from {{ pkg }} python package
  file:
    src: "/opt/{{ dir }}/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  with_items: "{{ bin }}"
