---
dependency:
  name: galaxy
driver:
  name: docker
  options:
    # options relevant if started with molecule `create -d delegated` to apply locally
    managed: False
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    pre_build_image: true
provisioner:
  name: ansible
  log: True
verifier:
  name: ansible
